// ── src/utils/mockData.js ──
// Replace API calls with real data from your FastAPI backend.
// Shape matches what the backend should return.

export const MOCK_JOBS = [
  {
    id: '1', title: 'Junior Python Developer', company: 'Zoho Corporation',
    location: 'Pan India', level: 'fresher', categories: ['fresher','it'],
    source: 'LinkedIn', work_type: 'Remote', remote: true,
    experience_range: '0–1 yr', salary_display: '₹4–6 LPA',
    company_rating: '4.3', company_stage: 'MNC · 10K+',
    deadline: 'Jun 30', ai_score: 94, is_new: true, posted_ago: '12m ago',
    is_hot: false,
    skills: [
      { name: 'Python', match: true }, { name: 'Django', match: true },
      { name: 'MySQL', match: false }, { name: 'REST APIs', match: true },
      { name: 'Git', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '2', title: 'Data Science Intern — ML & Analytics', company: 'Flipkart',
    location: 'Bangalore (Hybrid)', level: 'intern', categories: ['intern','data'],
    source: 'Internshala', work_type: 'Hybrid', remote: false,
    experience_range: 'Students / Freshers', salary_display: '₹15,000–25,000/mo',
    company_rating: '4.1', company_stage: 'Unicorn',
    deadline: 'Jul 15', ai_score: 91, is_new: true, posted_ago: '28m ago',
    is_hot: false,
    skills: [
      { name: 'Python', match: true }, { name: 'Pandas', match: true },
      { name: 'Scikit-learn', match: true }, { name: 'SQL', match: false },
      { name: 'Tableau', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '3', title: 'HR Executive — Talent Acquisition', company: 'Infosys BPM',
    location: 'Hyderabad (On-site)', level: 'fresher', categories: ['fresher','nonit'],
    source: 'Naukri', work_type: 'On-site', remote: false,
    experience_range: '0–2 yrs · MBA HR', salary_display: '₹3.5–5.5 LPA',
    company_rating: '3.9', company_stage: 'MNC · 50K+',
    deadline: null, ai_score: 82, is_new: false, posted_ago: '3h ago',
    is_hot: true, applicant_count: 127,
    skills: [
      { name: 'HR Operations', match: true }, { name: 'Recruitment', match: false },
      { name: 'MS Excel', match: false }, { name: 'Communication', match: true },
    ],
    apply_url: '#',
  },
  {
    id: '4', title: 'Junior Engineer (Civil/Electrical) — SSC JE 2024', company: 'Staff Selection Commission',
    location: 'All India', level: 'govt', categories: ['govt'],
    source: 'UPSC Portal', work_type: 'On-site', remote: false,
    experience_range: 'Diploma / BE / B.Tech', salary_display: '₹35,400–1,12,400/mo',
    company_rating: null, company_stage: 'Central Govt',
    deadline: 'Jul 20', ai_score: 71, is_new: false, posted_ago: '1d ago',
    is_hot: false,
    skills: [
      { name: 'Civil Engg', match: false }, { name: 'Electrical', match: false },
      { name: 'Govt Job', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '5', title: 'Junior ML Engineer — NLP / LLM Products', company: 'Sarvam AI',
    location: 'Bangalore / Remote', level: 'fresher', categories: ['fresher','data','it'],
    source: 'AngelList', work_type: 'Remote', remote: true,
    experience_range: '0–1 yr · B.Tech CS/AI', salary_display: '₹8–14 LPA',
    company_rating: '4.6', company_stage: 'Startup · Series A',
    deadline: null, ai_score: 96, is_new: true, posted_ago: '1h ago',
    is_hot: false,
    skills: [
      { name: 'Python', match: true }, { name: 'PyTorch', match: true },
      { name: 'Transformers', match: false }, { name: 'NLP', match: true },
      { name: 'LangChain', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '6', title: 'Full Stack Developer — React + Node.js', company: 'Razorpay',
    location: 'Hyderabad (Hybrid)', level: 'mid', categories: ['it'],
    source: 'LinkedIn', work_type: 'Hybrid', remote: false,
    experience_range: '2–4 yrs', salary_display: '₹18–28 LPA',
    company_rating: '4.4', company_stage: 'Unicorn · Series F',
    deadline: null, ai_score: 89, is_new: false, posted_ago: '5h ago',
    is_hot: false,
    skills: [
      { name: 'React', match: true }, { name: 'Node.js', match: true },
      { name: 'TypeScript', match: false }, { name: 'PostgreSQL', match: true },
      { name: 'AWS', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '7', title: 'Digital Marketing Intern', company: 'Groww',
    location: 'Bangalore / Remote', level: 'intern', categories: ['intern','nonit'],
    source: 'Internshala', work_type: 'Remote', remote: true,
    experience_range: 'Any Graduate', salary_display: '₹8,000–15,000/mo',
    company_rating: '4.2', company_stage: 'Unicorn',
    deadline: null, ai_score: 78, is_new: false, posted_ago: '6h ago',
    is_hot: false,
    skills: [
      { name: 'SEO/SEM', match: false }, { name: 'Google Analytics', match: false },
      { name: 'Meta Ads', match: false }, { name: 'Content Writing', match: true },
    ],
    apply_url: '#',
  },
  {
    id: '8', title: 'Financial Analyst — FP&A', company: 'HDFC Bank',
    location: 'Mumbai (Hybrid)', level: 'fresher', categories: ['fresher','nonit'],
    source: 'Indeed', work_type: 'Hybrid', remote: false,
    experience_range: '0–1 yr · CA / MBA Finance', salary_display: '₹6–9 LPA',
    company_rating: '4.0', company_stage: 'MNC · Banking',
    deadline: null, ai_score: 80, is_new: false, posted_ago: '8h ago',
    is_hot: false,
    skills: [
      { name: 'Financial Modeling', match: false }, { name: 'Excel', match: true },
      { name: 'Power BI', match: false }, { name: 'Tally', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '9', title: 'Senior Backend Engineer — Python / Distributed Systems', company: 'Swiggy',
    location: 'Hyderabad (Hybrid)', level: 'senior', categories: ['senior','it'],
    source: 'LinkedIn', work_type: 'Hybrid', remote: false,
    experience_range: '3–5 yrs', salary_display: '₹20–28 LPA',
    company_rating: '4.2', company_stage: 'Series H',
    deadline: null, ai_score: 97, is_new: true, posted_ago: '4m ago',
    is_hot: true, applicant_count: 43,
    skills: [
      { name: 'Python', match: true }, { name: 'FastAPI', match: true },
      { name: 'Redis', match: true }, { name: 'Kafka', match: false },
      { name: 'K8s', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '10', title: 'Apprentice Trainee — Engineering (BHEL 2024)', company: 'BHEL',
    location: 'Multiple Cities', level: 'govt', categories: ['govt'],
    source: 'BHEL Official', work_type: 'On-site', remote: false,
    experience_range: 'ITI / Diploma / BE', salary_display: '₹14,000–21,000/mo',
    company_rating: null, company_stage: 'Central PSU',
    deadline: 'Closing Soon', ai_score: 68, is_new: false, posted_ago: '2d ago',
    is_hot: false,
    skills: [
      { name: 'Electrical', match: false }, { name: 'Mechanical', match: false },
      { name: 'Civil', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '11', title: 'Frontend Developer (React/Vue) — Fresher Batch 2024', company: 'Wipro',
    location: 'Pan India', level: 'fresher', categories: ['fresher','it'],
    source: 'FreshersWorld', work_type: 'Remote', remote: true,
    experience_range: '0–1 yr · B.E/B.Tech/BCA', salary_display: '₹3.5–4.5 LPA',
    company_rating: '3.7', company_stage: 'MNC · 2L+ employees',
    deadline: null, ai_score: 85, is_new: true, posted_ago: '2h ago',
    is_hot: false,
    skills: [
      { name: 'React', match: true }, { name: 'JavaScript', match: true },
      { name: 'HTML/CSS', match: true }, { name: 'Vue.js', match: false },
    ],
    apply_url: '#',
  },
  {
    id: '12', title: 'Data Engineer — Spark / Databricks / GCP', company: 'PhonePe',
    location: 'Hyderabad (Hybrid)', level: 'mid', categories: ['data','it'],
    source: 'Naukri', work_type: 'Hybrid', remote: false,
    experience_range: '2–4 yrs', salary_display: '₹16–24 LPA',
    company_rating: '4.4', company_stage: 'Walmart-backed',
    deadline: null, ai_score: 88, is_new: false, posted_ago: '4h ago',
    is_hot: false,
    skills: [
      { name: 'Python', match: true }, { name: 'Apache Spark', match: false },
      { name: 'Databricks', match: false }, { name: 'GCP BigQuery', match: false },
      { name: 'Airflow', match: false },
    ],
    apply_url: '#',
  },
];
